name: Docker Image CI

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: build ${{ matrix.php-version }} - ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
        platform:
          - alpine
          - bullseye
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build -t yansongda/php-fpm -f ./${{ matrix.php-version }}/${{ matrix.platform }}/Dockerfile ./${{ matrix.php-version }}
    - name: Tag the image
      run: |
        docker tag yansongda/php-fpm yansongda/php-fpm:${{ matrix.php-version }}-${{ matrix.platform }}
        docker tag yansongda/php-fpm registry.cn-shenzhen.aliyuncs.com/yansongda/php-fpm:${{ matrix.php-version }}-${{ matrix.platform }}
    - name: Push the image to docker registry
      run: |
        docker login --username yansongda -p ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
        docker push yansongda/php-fpm:${{ matrix.php-version }}-${{ matrix.platform }}
    - name: Push the image to aliyun registry
      run: |
        docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com -p ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}
        docker push registry.cn-shenzhen.aliyuncs.com/yansongda/php-fpm:${{ matrix.php-version }}-${{ matrix.platform }}
