name: Docker Image CI

on:
  push:
    branchs:
      - master
  schedule:
    - cron: '0 0 * * 1'

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: build ${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.system }}-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
        php-mode:
          - fpm
          - cli
        system:
          - alpine
          - bullseye
        platform:
          - linux/arm64
          - linux/amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Recognize tag
      run: |
        arm64='linux/arm64'
        tag=${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.system }}

        if (( $arm64 == ${{ matrix.platform }} )); then
          tag='arm64-'$tag
        fi

        echo $tag
    - name: Build the docker image
      run: |
        docker buildx build -t yansongda/php --platform=${{ matrix.platform }} -f ./${{ matrix.php-version }}/${{ matrix.php-mode }}/${{ matrix.system }}/Dockerfile ./${{ matrix.php-version }}/${{ matrix.php-mode }}
    - name: Tag the image
      run: |
        docker tag yansongda/php yansongda/php:$tag
        docker tag yansongda/php registry.cn-shenzhen.aliyuncs.com/yansongda/php:$tag
    - name: Push the image to docker registry
      run: |
        echo $DOCKERHUB_ACCESSTOKEN | docker login --username yansongda --password-stdin
        docker push yansongda/php:$tag
        docker logout
    - name: Push the image to aliyun registry
      run: |
        echo $ALIYUN_IMAGE_ACCESSTOKEN | docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com --password-stdin
        docker push registry.cn-shenzhen.aliyuncs.com/yansongda/php:$tag
        docker logout
