name: Docker Image CI

on:
  push:
    branchs:
      - master
  schedule:
    - cron: '0 0 * * 1'

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: build ${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
        php-mode:
          - fpm
          - cli
        platform:
          - alpine
          - bullseye
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build -t yansongda/php -f ./${{ matrix.php-version }}/${{ matrix.php-mode }}/${{ matrix.platform }}/Dockerfile ./${{ matrix.php-version }}/${{ matrix.php-mode }}
    - name: Tag the image
      run: |
        docker tag yansongda/php yansongda/php:${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.platform }}
        docker tag yansongda/php registry.cn-shenzhen.aliyuncs.com/yansongda/php:${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.platform }}
    - name: Push the image to docker registry
      run: |
        echo ${{ secrets.DOCKERHUB_ACCESSTOKEN }} | docker login --username yansongda --password-stdin
        docker push yansongda/php:${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.platform }}
        docker logout
    - name: Push the image to aliyun registry
      run: |
        echo ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }} | docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com --password-stdin
        docker push registry.cn-shenzhen.aliyuncs.com/yansongda/php:${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.platform }}
        docker logout
